# Generated by Django 5.0.2 on 2024-02-24 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Group`s name")),
            ],
        ),
        migrations.CreateModel(
            name="Musician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        default="ali", max_length=50, verbose_name="person's first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        default="ahmadi",
                        max_length=50,
                        verbose_name="person's last name",
                    ),
                ),
                (
                    "instrument",
                    models.CharField(
                        choices=[
                            ("Flute", "f"),
                            ("Harp", "h"),
                            ("Cello", "c"),
                            ("Drums", "d"),
                            ("Guitar", "g"),
                            ("Saxophone", "a"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_joined", models.DateField()),
                ("invite_reason", models.CharField(max_length=64)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="OrmApp.group"
                    ),
                ),
                (
                    "musician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="OrmApp.musician",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                through="OrmApp.Membership", to="OrmApp.musician"
            ),
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Albums name")),
                (
                    "release_date",
                    models.DateField(help_text="the year that Album published"),
                ),
                ("num_stars", models.IntegerField()),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="OrmApp.musician",
                    ),
                ),
            ],
        ),
    ]
