# Generated by Django 5.0.2 on 2024-02-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("OrmApp", "0002_alter_album_table_alter_group_table_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="musician",
            table=None,
        ),
    ]
