# Generated by Django 5.0.2 on 2024-02-24 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("OrmApp", "0003_alter_musician_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="album",
            table=None,
        ),
        migrations.AlterModelTable(
            name="group",
            table=None,
        ),
        migrations.AlterModelTable(
            name="membership",
            table=None,
        ),
    ]
