# Generated by Django 5.0.2 on 2024-02-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrmApp", "0004_alter_album_table_alter_group_table_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="musician",
            options={"ordering": ["last_name"]},
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("birth_date", models.DateField()),
                (
                    "m2m",
                    models.ManyToManyField(
                        related_name="%(app_label)s_%(class)s_related",
                        related_query_name="%(app_label)s_%(class)ss",
                        to="OrmApp.musician",
                    ),
                ),
            ],
            options={
                "db_table": "Person",
                "abstract": False,
            },
        ),
    ]
