# Generated by Django 5.0.2 on 2024-02-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_lesson_package_student_description_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="package",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
