# Generated by Django 5.0.2 on 2024-03-04 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_alter_lesson_name_alter_package_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="package",
            options={"ordering": ["name"]},
        ),
    ]
